# Generated by Django 3.0.5 on 2020-04-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choise_text',
            new_name='choice_text',
        ),
    ]
